# For the nav bar
urls:
    
    - text: Resume
      url: /assets/RajwritaNathResume.pdf
    - text: Kolkata 70
      url: /kol70
#     - text: Kitchen
#       url: "https://rajwritacooks.framer.website/"
#     - text: Work Ex
#       url: /work
#     - text: Projects
#       url: /projects
#     - text: Posts
#       url: /posts
#     - text: Talks
#       url: /talks


title: Rajwrita
email: rajwritanath@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rajwrita.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rajwrita
github_username:  Rajwrita

# Google Analytics
google_analytics: UA-196489576-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

disqus: true
disqus_shortname: 'Rajwrita'

# For hihlighting code
highlighter: rouge
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

